### ISSUE TITLE
Using Background Images in Vanilla CSS

### ISSUE THREAD

**Issue by grayghostvisuals** [jekyll-assets/jekyll-assets#156]
I have a project that uses Vanilla CSS and unfortunately cannot get any bg images to carry over to my compiled _site destination. Is there a way around to use Vanilla CSS while still using this plugin?

**Comment by ixti** [comment]
You can use ERB for that. Let's say you have `app.css` file, rename it to `app.css.erb` and put under some `jekyll-assets` lookup path, by default it will be `_assets/stylesheets`. Now you can use ERB inside of your `app.css`:

``` css
body { cbackground-image: url('<%= image_path "bg.jpg" %>') }
```
